import os

SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(SOURCE_DIR + '/../')
ID_HAIRPRO_SHEET = '1u7dCTQzbqgKSSjpSVtsUl7ea2j2YgW4Ko2nB9akE1ws'
GOOGLE_API_CREDENTIALS = os.path.join(ROOT_DIR, 'credentials/google_api.json')
PRICING_MANAGER_FILE = os.path.join(ROOT_DIR, 'settings/pricing_manager.json')
COLUMNS_ALL_SELLER = [
    'sku',
    'brand',
    'category',
    'product_name',
    'price',
    'seller_name',
]
COLUMNS_EXCEPT_HAIRPRO = [
    'sku',
    'brand',
    'category',
    'product_name',
    'price',
    'seller_name',
]
COLUMNS_HAIRPRO = [
    'sku',
    'brand',
    'category',
    'product_name',
    'price',
    'seller_name',
]
COLUMNS_DIFERENCE = [
    COLUMNS_HAIRPRO[0],
    COLUMNS_HAIRPRO[1],
    'category',
    'product_name',
    COLUMNS_HAIRPRO[4],
    'competitor_price',
    'difference_price',
    'suggest_price',
    'ganho_%',
]
COLUMNS_RESULT = [
    'sku',
    'sku (*)',
    'sku_parent',
    'name (*)',
    'quantity (*)',
    'price (*)',
    'special_price',
    'description',
    'brand',
    'link',
    'warranty_time',
    'warranty_message',
    'length',
    'width',
    'height',
    'weight',
    'ean',
    'isbn',
    'ncm',
    'nbm',
    'link_image_1',
    'link_image_2',
    'link_image_3',
    'link_image_4',
    'link_image_5',
    'link_image_6',
    'link_image_7',
    'link_image_8',
    'link_image_9',
    'link_image_10',
    'attribute_name_1',
    'attribute_value_1',
    'attribute_name_2',
    'attribute_value_2',
    'attribute_name_3',
    'attribute_value_3',
    'attribute_name_4',
    'attribute_value_4',
    'attribute_name_5',
    'attribute_value_5',
    'attribute_name_6',
    'attribute_value_6',
    'attribute_name_7',
    'attribute_value_7',
    'attribute_name_8',
    'attribute_value_8',
    'attribute_name_9',
    'attribute_value_9',
    'attribute_name_10',
    'attribute_value_10',
    'attribute_name_11',
    'attribute_value_11',
    'attribute_name_12',
    'attribute_value_12',
    'attribute_name_13',
    'attribute_value_13',
    'attribute_name_14',
    'attribute_value_14',
    'attribute_name_15',
    'attribute_value_15',
    'attribute_name_16',
    'attribute_value_16',
    'attribute_name_17',
    'attribute_value_17',
    'attribute_name_18',
    'attribute_value_18',
    'attribute_name_19',
    'attribute_value_19',
    'attribute_name_20',
    'attribute_value_20',
    'attribute_name_21',
    'attribute_value_21',
    'attribute_name_22',
    'attribute_value_22',
    'attribute_name_23',
    'attribute_value_23',
    'attribute_name_24',
    'attribute_value_24',
    'attribute_name_25',
    'attribute_value_25',
    'attribute_name_26',
    'attribute_value_26',
    'attribute_name_27',
    'attribute_value_27',
    'attribute_name_28',
    'attribute_value_28',
    'attribute_name_29',
    'attribute_value_29',
    'attribute_name_30',
    'attribute_value_30',
    'full_category_tree_1 (ie: base > cat > subcat > subsubcat)',
    'full_category_tree_2 (ie: base > cat > subcat > subsubcat)',
    'full_category_tree_3 (ie: base > cat > subcat > subsubcat)',
    'handling_time',
    'manufacture_time',
    'model',
    'cest',
    'location',
    'ean_not_mandatory',
    'cost',
    'origin',
    'marketplaces_available',
]